#!/bin/zsh

# arch切り替えのためにzshrcで処理する
# # uname -m コマンドを使ってマシンのアーキテクチャを取得
# arch=$(uname -m)
# 
# # アーキテクチャが "arm64" なら M1以降のMac
# if [ "$arch" = "arm64" ]; then
#     eval $(/opt/homebrew/bin/brew shellenv)
# fi

# Created by `pipx` on 2024-12-26 22:56:33
export PATH="$PATH:/Users/number09/.local/bin"
