[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


[[plugins]]
repo = 'Shougo/unite.vim'


[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = ['Shougo/unite.vim']

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'davidhalter/jedi-vim'

#[[plugins]]
#repo = 'lambdalisue/vim-pyenv'
#depends = ['davidhalter/jedi-vim']
#on_ft = ["python","python3","djangohtml"]

[[plugins]]
repo = 'majutsushi/tagbar'


[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'othree/html5.vim'

# [[plugins]]
# repo = 'taichouchou2/vim-javascript'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'mrtazz/simplenote.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
