name: CI

on:
  push:
  pull_request:

jobs:
  testcommand :
    name: Test Command
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Workaround for https://github.com/actions/setup-python/issues/577
      - name: Clean up python binaries
        run: |
          rm -f /usr/local/bin/2to3*;
          rm -f /usr/local/bin/idle3*;
          rm -f /usr/local/bin/pydoc3*;
          rm -f /usr/local/bin/python3*;
          rm -f /usr/local/bin/python3*-config;
      - name: Delete default awscli
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
      - name: ls
        run: ls
      - name: init
        run: sh scripts/init.sh
      - name: mac_setup
        run: sh scripts/mac_setup.sh
      - name: brew tap install
        run: brew bundle --file ./apps/homebrew/Brewfile-tap
      - name: app install
        run: brew bundle --file ./apps/homebrew/Brewfile-common
      - name: app setup
        run: sh scripts/setup_all.sh
      - name: zsh
        shell: zsh {0}
        run: source ~/.zshrc
      - name: after setup
        shell: zsh {0}
        run: sh scripts/after_setup_all.sh

  testmake :
    name: Test make
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Workaround for https://github.com/actions/setup-python/issues/577
      - name: Clean up python binaries
        run: |
          rm -f /usr/local/bin/2to3*;
          rm -f /usr/local/bin/idle3*;
          rm -f /usr/local/bin/pydoc3*;
          rm -f /usr/local/bin/python3*;
          rm -f /usr/local/bin/python3*-config;
      - name: Delete default awscli
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
      - name: make init
        run: make init
      - name: mac setup
        run: make mac_setup
      - name: install
        run: make install-common
